profiles:
  qwen_local_35b_9b:
    big:
      role_model_name: "openai/qwen2.5-coder:1.5b"
      client_model_name: "openai/local-model"
      api_base: "http://127.0.0.1:11434/v1"
      api_key: "EMPTY"
      max_input_tokens: 300000
    small:
      role_model_name: "openai/qwen2.5-coder:1.5b"
      client_model_name: "openai/local-model"
      api_base: "http://127.0.0.1:11434/v1"
      api_key: "EMPTY"
      max_input_tokens: 300000

  gptoss120b_big_qwen35b_small:
    big:
      role_model_name: "openai/openai/gpt-oss-120b"
      client_model_name: "openai/local-model"
      api_base: "http://promaxgb10-d473.eecs.umich.edu:8000/v1"
      api_key: "api_IcLlffdxoWOSgBPWW3X3zS15YSBHim5a"
      max_input_tokens: 300000
    small:
      role_model_name: "openai/qwen2.5-coder:1.5b"
      client_model_name: "openai/local-model"
      api_base: "http://127.0.0.1:11434/v1"
      api_key: "EMPTY"
      max_input_tokens: 300000

  gptoss120b_big_qwen9b_small:
    big:
      role_model_name: "openai/openai/gpt-oss-120b"
      client_model_name: "openai/local-model"
      api_base: "http://promaxgb10-d473.eecs.umich.edu:8000/v1"
      api_key: "api_IcLlffdxoWOSgBPWW3X3zS15YSBHim5a"
      max_input_tokens: 300000
    small:
      role_model_name: "openai/qwen2.5-coder:1.5b"
      client_model_name: "openai/local-model"
      api_base: "http://127.0.0.1:11434/v1"
      api_key: "EMPTY"
      max_input_tokens: 300000

  gptoss120b_all:
    big:
      role_model_name: "openai/openai/gpt-oss-120b"
      client_model_name: "openai/local-model"
      api_base: "http://promaxgb10-d473.eecs.umich.edu:8000/v1"
      api_key: "api_IcLlffdxoWOSgBPWW3X3zS15YSBHim5a"
      max_input_tokens: 300000
    small:
      role_model_name: "openai/openai/gpt-oss-120b"
      client_model_name: "openai/local-model"
      api_base: "http://promaxgb10-d473.eecs.umich.edu:8000/v1"
      api_key: "api_IcLlffdxoWOSgBPWW3X3zS15YSBHim5a"
      max_input_tokens: 300000

sweeps:
  default:
    - "qwen_local_35b_9b"
    - "gptoss120b_big_qwen35b_small"
    - "gptoss120b_big_qwen9b_small"
    - "gptoss120b_all"
