output_dir: "trajectories/small_coder_only/"

instances:
  type: swe_bench
  subset: lite
  split: dev
  shuffle: true
  slice: ":10"
  evaluate: true
  deployment:
    type: docker
    python_standalone_dir: ""
    pull: missing

agent:
  type: multi_3_models

  planner: openai/qwen/qwen3.5-35b-a3b
  coder: openai/qwen/qwen3.5-9b
  reviewer: openai/qwen/qwen3.5-35b-a3b
  enable_planner: false
  enable_reviewer: false

  model:
    name: openai/local-model
    per_instance_cost_limit: 0
    per_instance_call_limit: 100
    temperature: 0.1
    api_key: lm-studio
    api_base: http://127.0.0.1:1234/v1
    max_input_tokens: 300000
    total_cost_limit: 0

  templates:
    system_template: |-
      Empty
    instance_template: |-
      Empty
  roles: {}

  tools:
    env_variables:
      PAGER: cat
      MANPAGER: cat
      LESS: -R
      PIP_PROGRESS_BAR: "off"
      TQDM_DISABLE: "1"
      GIT_PAGER: cat
    bundles:
      - path: tools/registry
      - path: tools/edit_anthropic
      - path: tools/handoff
      - path: tools/submit
    registry_variables:
      USE_FILEMAP: "true"
    enable_bash_tool: true
    parse_function:
      type: thought_action

  history_processors:
    - type: cache_control
      last_n_messages: 2
