presets:
  openai_gpt4o_mini:
    backend: openai
    model: gpt-4o-mini
    api_base: https://api.openai.com/v1
    tool_call_mode: openai_tools

  lmstudio_local:
    backend: lmstudio
    model: openai/local-model
    api_base: http://127.0.0.1:1234/v1
    tool_call_mode: openai_tools

  umich_gptoss_120b:
    backend: umich
    model: openai/openai/gpt-oss-120b
    api_base: http://promaxgb10-d473.eecs.umich.edu:8000/v1
    tool_call_mode: openai_tools
    api_key: api_IcLlffdxoWOSgBPWW3X3zS15YSBHim5a

  umich_qwen:
    backend: umich
    model: openai/Qwen/Qwen3-VL-30B-A3B-Instruct
    api_base: http://promaxgb10-d668.eecs.umich.edu:8000/v1
    tool_call_mode: react_json
    api_key: api_RPnuSxgxJQamqW04ma9uJW27vc4TyBdy

  ollama_qwen35_9b:
    backend: ollama
    model: qwen3.5:9b
    api_base: http://localhost:11434
    tool_call_mode: react_json
